/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author AFRIAN
 */
public class DaftarPulau extends javax.swing.JFrame {

    /**
     * Creates new form DaftarPulau
     */
    public DaftarPulau() {
        initComponents();
        // mengambil ukuran layar
        Dimension layar = Toolkit.getDefaultToolkit().getScreenSize();

        // membuat titik x dan y
        int x = layar.width / 2  - this.getSize().width / 2;
        int y = layar.height / 2 - this.getSize().height / 2;

        this.setLocation(x, y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        bt_weh = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        bt_kanawa = new javax.swing.JButton();
        bt_derawan = new javax.swing.JButton();
        label_weh = new javax.swing.JLabel();
        label_kanawa = new javax.swing.JLabel();
        label_derawan = new javax.swing.JLabel();
        bt_menu = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));
        jPanel1.setLayout(null);

        bt_weh.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        bt_weh.setText("PULAU SAPUDI");
        bt_weh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_wehActionPerformed(evt);
            }
        });
        jPanel1.add(bt_weh);
        bt_weh.setBounds(50, 260, 281, 50);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("RIWAYAT PEMESANAN");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(187, 30, 356, 40);

        bt_kanawa.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        bt_kanawa.setText("PULAU KANAWA");
        bt_kanawa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_kanawaActionPerformed(evt);
            }
        });
        jPanel1.add(bt_kanawa);
        bt_kanawa.setBounds(410, 260, 281, 50);

        bt_derawan.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        bt_derawan.setText("PULAU DERAWAN");
        bt_derawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_derawanActionPerformed(evt);
            }
        });
        jPanel1.add(bt_derawan);
        bt_derawan.setBounds(230, 490, 281, 50);

        label_weh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/download.jpg"))); // NOI18N
        label_weh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_wehMouseClicked(evt);
            }
        });
        jPanel1.add(label_weh);
        label_weh.setBounds(50, 90, 281, 155);

        label_kanawa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Pulau Kanawa (3).jpg"))); // NOI18N
        label_kanawa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_kanawaMouseClicked(evt);
            }
        });
        jPanel1.add(label_kanawa);
        label_kanawa.setBounds(410, 90, 281, 155);

        label_derawan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Pulau Derawan (2).jpg"))); // NOI18N
        label_derawan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_derawanMouseClicked(evt);
            }
        });
        jPanel1.add(label_derawan);
        label_derawan.setBounds(230, 320, 281, 155);

        bt_menu.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        bt_menu.setText("Menu");
        bt_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_menuActionPerformed(evt);
            }
        });
        jPanel1.add(bt_menu);
        bt_menu.setBounds(600, 500, 110, 40);

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 1, 10)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon("D:\\KULIAH UIN MALANG\\kuliah semester 2\\Prak. PBO\\Project UAS\\bck senja (1).jpg")); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(0, 0, 750, 560);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_wehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_wehActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new PulauSapudi().setVisible(true);
    }//GEN-LAST:event_bt_wehActionPerformed

    private void label_wehMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_wehMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new PulauSapudi().setVisible(true);
    }//GEN-LAST:event_label_wehMouseClicked

    private void bt_kanawaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_kanawaActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new PulauKanawa().setVisible(true);
    }//GEN-LAST:event_bt_kanawaActionPerformed

    private void label_kanawaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_kanawaMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new PulauKanawa().setVisible(true);
    }//GEN-LAST:event_label_kanawaMouseClicked

    private void bt_derawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_derawanActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new PulauDerawan().setVisible(true);
    }//GEN-LAST:event_bt_derawanActionPerformed

    private void label_derawanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_derawanMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new PulauDerawan().setVisible(true);
    }//GEN-LAST:event_label_derawanMouseClicked

    private void bt_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_menuActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Menu().setVisible(true);
    }//GEN-LAST:event_bt_menuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DaftarPulau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DaftarPulau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DaftarPulau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DaftarPulau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DaftarPulau().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_derawan;
    private javax.swing.JButton bt_kanawa;
    private javax.swing.JButton bt_menu;
    private javax.swing.JButton bt_weh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label_derawan;
    private javax.swing.JLabel label_kanawa;
    private javax.swing.JLabel label_weh;
    // End of variables declaration//GEN-END:variables
}
