/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Connection.koneksi;
import Objek.Paket1Day;
import Objek.WisataPulau;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ach. Afrian Auliansyah
 */
public class OneDay extends javax.swing.JFrame {   
    //refrensi variabel dan objek
    WisataPulau ondy = new Paket1Day();
    
    public DefaultTableModel model;
    private ResultSet hasil;

    /**
     * Creates new form OneDay
     */
    
    public OneDay() {
        initComponents();
        // mengambil ukuran layar
        Dimension layar = Toolkit.getDefaultToolkit().getScreenSize();

        // membuat titik x dan y
        int x = layar.width / 2  - this.getSize().width / 2;
        int y = layar.height / 2 - this.getSize().height / 2;

        this.setLocation(x, y);
        
        //Data Paket 1 Day
        String[] judul1 = {"Nama Pemesan","Pulau","Tanggal","Paket Harga"};
        model = new DefaultTableModel(judul1, 0);
        tabeldata_day1.setModel(model);
        tabelday1();
    }
    
    public void tabelday1() {
        try {
            hasil = ondy.PrintData();
            while (hasil.next()) {
                ondy.setNama(hasil.getString("Nama Pemesan"));
                ondy.setPulau(hasil.getString("Pulau"));
                ondy.setTanggal(hasil.getString("Tanggal"));
                ondy.setPaketharga(hasil.getString("Paket Harga"));

                String[] data = {ondy.getNama(), ondy.getPulau(), ondy.getTanggal(), ondy.getPaketharga()};
                model.addRow(data);
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }
    
    public void Reset() {
        txt_nama.setText("");
        combo_pulau.setSelectedItem("");
        txt_tanggal.setText("");
        combo_paketharga.setSelectedItem("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        bt_kembali = new javax.swing.JButton();
        bt_perbarui = new javax.swing.JButton();
        bt_hapus = new javax.swing.JButton();
        bt_pesan = new javax.swing.JButton();
        bt_checkout = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabeldata_day1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txt_nama = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        combo_paketharga = new javax.swing.JComboBox<>();
        txt_tanggal = new javax.swing.JTextField();
        combo_pulau = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(670, 550));
        jPanel1.setLayout(null);

        bt_kembali.setFont(new java.awt.Font("Tw Cen MT", 1, 20)); // NOI18N
        bt_kembali.setText("Kembali");
        bt_kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_kembaliActionPerformed(evt);
            }
        });
        jPanel1.add(bt_kembali);
        bt_kembali.setBounds(585, 489, 110, 40);

        bt_perbarui.setFont(new java.awt.Font("Tw Cen MT", 1, 20)); // NOI18N
        bt_perbarui.setText("Perbarui");
        bt_perbarui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_perbaruiActionPerformed(evt);
            }
        });
        jPanel1.add(bt_perbarui);
        bt_perbarui.setBounds(48, 489, 110, 40);

        bt_hapus.setFont(new java.awt.Font("Tw Cen MT", 1, 20)); // NOI18N
        bt_hapus.setText("Hapus");
        bt_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_hapusActionPerformed(evt);
            }
        });
        jPanel1.add(bt_hapus);
        bt_hapus.setBounds(169, 489, 110, 40);

        bt_pesan.setFont(new java.awt.Font("Tw Cen MT", 1, 20)); // NOI18N
        bt_pesan.setText("Pesan");
        bt_pesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_pesanActionPerformed(evt);
            }
        });
        jPanel1.add(bt_pesan);
        bt_pesan.setBounds(585, 295, 110, 40);

        bt_checkout.setFont(new java.awt.Font("Tw Cen MT", 1, 20)); // NOI18N
        bt_checkout.setText("Checkout");
        bt_checkout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_checkoutActionPerformed(evt);
            }
        });
        jPanel1.add(bt_checkout);
        bt_checkout.setBounds(291, 489, 110, 40);

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("PAKET 1 DAY");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(270, 30, 211, 40);

        tabeldata_day1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nama Pemesan", "Pulau", "Tanggal", "Paket Harga"
            }
        ));
        tabeldata_day1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabeldata_day1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabeldata_day1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(48, 348, 647, 128);

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Pulau");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(47, 146, 75, 27);

        txt_nama.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(txt_nama);
        txt_nama.setBounds(225, 95, 260, 36);

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Tanggal");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(47, 195, 83, 27);

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nama pemesan");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(47, 99, 160, 27);

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Paket Harga");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(47, 240, 124, 27);

        combo_paketharga.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        combo_paketharga.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Paket 1 [100K]", "Paket 2 [200K]", "Paket 3 [300K]" }));
        jPanel1.add(combo_paketharga);
        combo_paketharga.setBounds(225, 240, 165, 36);

        txt_tanggal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(txt_tanggal);
        txt_tanggal.setBounds(225, 191, 165, 36);

        combo_pulau.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        combo_pulau.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pulau Derawan", "Pulau Kanawa", "Pulau Sapudi" }));
        jPanel1.add(combo_pulau);
        combo_pulau.setBounds(225, 142, 165, 36);

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 1, 10)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon("D:\\KULIAH UIN MALANG\\kuliah semester 2\\Prak. PBO\\Project UAS\\bck senja (1).jpg")); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(0, 0, 750, 560);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 743, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabeldata_day1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabeldata_day1MouseClicked
        // TODO add your handling code here:
        // menampilkan data kedalam form pengisian:
        int baris = tabeldata_day1.getSelectedRow();
        if(baris > -1){
            String nama = tabeldata_day1.getValueAt(baris, 0).toString();
            txt_nama.setText(nama);
            String pulau = tabeldata_day1.getValueAt(baris,1).toString();
            combo_pulau.setSelectedItem(pulau);
            String tanggal = tabeldata_day1.getValueAt(baris, 2).toString();
            txt_tanggal.setText(tanggal);
            String paketharga = tabeldata_day1.getValueAt(baris, 3).toString();
            combo_paketharga.setSelectedItem(paketharga);
        }
    }//GEN-LAST:event_tabeldata_day1MouseClicked

    private void bt_checkoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_checkoutActionPerformed
        // TODO add your handling code here:
        Reset();
        JOptionPane.showMessageDialog(null, "Pesanan anda telah di checkout");
    }//GEN-LAST:event_bt_checkoutActionPerformed

    private void bt_pesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_pesanActionPerformed
        // TODO add your handling code here:
        try {
            ondy.setNama(txt_nama.getText());
            ondy.setPulau(combo_pulau.getSelectedItem().toString());
            ondy.setTanggal(txt_tanggal.getText());
            ondy.setPaketharga(combo_paketharga.getSelectedItem().toString());

            ondy.day(
                ondy.getNama(),
                ondy.getPulau(),
                ondy.getTanggal(),
                ondy.getPaketharga()
            );
            JOptionPane.showMessageDialog(null, "Data berhasil tersimpan");
            Reset();
        } catch (Exception e) {
            System.out.println(e);
        }
        this.setVisible(false);
        new OneDay().setVisible(true);
    }//GEN-LAST:event_bt_pesanActionPerformed

    private void bt_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_hapusActionPerformed
        // TODO add your handling code here:
        try {
            String sql ="DELETE FROM day1";
            java.sql.Connection conn=(Connection)koneksi.koneksiDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(this, "Pesanan Anda Telah Dihapus!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        Reset();
        this.setVisible(false);
        new OneDay().setVisible(true);
    }//GEN-LAST:event_bt_hapusActionPerformed

    private void bt_perbaruiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_perbaruiActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new OneDay().setVisible(true);
    }//GEN-LAST:event_bt_perbaruiActionPerformed

    private void bt_kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_kembaliActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Menu().setVisible(true);
    }//GEN-LAST:event_bt_kembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OneDay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OneDay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OneDay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OneDay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OneDay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_checkout;
    private javax.swing.JButton bt_hapus;
    private javax.swing.JButton bt_kembali;
    private javax.swing.JButton bt_perbarui;
    private javax.swing.JButton bt_pesan;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> combo_paketharga;
    private javax.swing.JComboBox<String> combo_pulau;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabeldata_day1;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_tanggal;
    // End of variables declaration//GEN-END:variables

}
